import type { Event } from '@/types/event';

export const fallbackEvents: Event[] = [
  {
    id: 'fallback-1',
    title: 'Coffee & Code Study Jam',
    date: { when: 'Sat, May 16 · 9:00 AM' },
    address: ['Mishka\'s Cafe', 'Davis, CA'],
    description: 'Bring your laptop and grind through homework or side projects with the local dev crowd.',
    tags: ['Study', 'Community'],
    thumbnail: 'https://images.unsplash.com/photo-1521017432531-fbd92d768814?w=240&q=70',
    source: 'fallback',
  },
  {
    id: 'fallback-2',
    title: 'Aggie Football Watch Party',
    date: { when: 'Sat, May 16 · 6:00 PM' },
    address: ['Sudwerk Brewing', 'Davis, CA'],
    description: 'Big screens, cold beer, and Aggie pride. Come early — last time it was packed.',
    tags: ['Sports', 'Social'],
    thumbnail: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=240&q=70',
    source: 'fallback',
  },
  {
    id: 'fallback-3',
    title: 'Farmers Market Lunch Crawl',
    date: { when: 'Sun, May 17 · 11:00 AM' },
    address: ['Central Park', 'Davis, CA'],
    description: 'Eat your way through the Sunday market with new faces. We hit five stalls in two hours.',
    tags: ['Food', 'Outdoor'],
    thumbnail: 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=240&q=70',
    source: 'fallback',
  },
  {
    id: 'fallback-4',
    title: 'Indie Game Night',
    date: { when: 'Fri, May 15 · 7:30 PM' },
    address: ['Sophia\'s Thai Bar', 'Davis, CA'],
    description: 'Switch + Steam Deck setup, snack wall, casual tournaments. All skill levels.',
    tags: ['Gaming', 'Social'],
    thumbnail: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=240&q=70',
    source: 'fallback',
  },
  {
    id: 'fallback-5',
    title: 'Open Mic at G Street',
    date: { when: 'Thu, May 14 · 8:00 PM' },
    address: ['G Street Wunderbar', 'Davis, CA'],
    description: 'Sign-ups at 7:30. Bring a song, a poem, or just come listen.',
    tags: ['Music', 'Social'],
    thumbnail: 'https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=240&q=70',
    source: 'fallback',
  },
  {
    id: 'fallback-6',
    title: 'Sunrise Hike: Putah Creek',
    date: { when: 'Sun, May 17 · 6:15 AM' },
    address: ['Putah Creek Reserve', 'Davis, CA'],
    description: 'Easy 3-mile loop. Coffee at the trailhead — bring a mug.',
    tags: ['Outdoor', 'Sports'],
    thumbnail: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=240&q=70',
    source: 'fallback',
  },
  {
    id: 'fallback-7',
    title: 'Spring Career Fair: Tech & Beyond',
    date: { when: 'Wed, May 20 · 12:00 PM' },
    address: ['UC Davis ARC Pavilion', 'Davis, CA'],
    description: '60+ employers, drop-in resume reviews, and free swag. Business casual.',
    tags: ['Career', 'Networking'],
    thumbnail: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=240&q=70',
    source: 'fallback',
  },
  {
    id: 'fallback-8',
    title: 'Community Garden Volunteer Day',
    date: { when: 'Sat, May 16 · 10:00 AM' },
    address: ['Davis Community Garden', 'Davis, CA'],
    description: 'Planting tomatoes and pulling weeds. Tools, gloves, and lemonade provided.',
    tags: ['Volunteer', 'Community'],
    thumbnail: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=240&q=70',
    source: 'fallback',
  },
];
